/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package banderas;

import banderas.clases.pais;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTextField;
import javax.swing.ListCellRenderer;

/**
 *
 * @author Alumno avanzado
 */
public class Banderas_render extends javax.swing.JPanel implements ListCellRenderer{
JLabel label=new JLabel();
    JTextField txt= new JTextField();
    
    public Banderas_render() {
        initComponents();
        
        setPreferredSize(new Dimension(300,100));
        setLayout(null);
        label.setHorizontalAlignment(JLabel.LEADING);
        label.setHorizontalAlignment(JLabel.CENTER);
        label.setIconTextGap(15);
        label.setBounds(10,10,200,80);
        add(label);
        txt.setBounds(230,10,100,80);
        add(txt);
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Banderas_render.class.getName());
    /**
     * Creates new form Banderas_a
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>                

    @Override
    public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        if (isSelected) {
            setBackground(list.getSelectionBackground());
            setBackground(list.getSelectionForeground());
        } else {
            setBackground(list.getBackground());
            setBackground(list.getForeground());
        }
        
        ImageIcon icon = ((pais)value).getIcono();
        label.setIcon(icon);
        label.setText(((pais)value).getNombre());
        txt.setText(((pais)value).getNombre());
        
        return label;
    }
    /**
     * Creates new form Banderas_b
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
